version: '3.7'
services:
    jenkins:
        build:
            context: ./
            args:
                HOST_UID: ${HOST_UID}
                HOST_GID: ${HOST_GID}
        image: ${DOCKER_USER}/${DOCKER_IMAGE}
        container_name: local-jenkins
        privileged: true
        restart: unless-stopped
        environment:
            - "JAVA_OPTS=-Xmx3g -Xms2G"
        volumes:
            - ${HOST_DOCKER}:/var/run/docker.sock
            - jenkins-data:/var/jenkins_home
        ports:
            - "${HOST_WWW}:8080"
            - "${HOST_OTHER}:50000"
volumes:
    jenkins-data: